env = Environment(CPPPATH=["/usr/local/include", 
			   "/usr/local/include/cantera/ext"],
                  CCFLAGS=["-std=c++11", "-Wall", "-Wno-inline", "-O0", "-g",
                           "-fprofile-arcs", "-ftest-coverage", "-pthread"],
                  LINKFLAGS = ["-fprofile-arcs", 
			       "-ftest-coverage", "-pthread", 
			       "-g", "-std=c++11"])

sources = ["main.cpp", "util.cpp", "zerodReactor.cpp", "onedReactor.cpp", 
           "io.cpp", "pfr1d.cpp", "pfr1d_solver.cpp", #"hctexceptions.cpp", 
           "IdealGasTRampReactor.cpp", "reactor_parser.cpp",
           ]

env.Program(target="omkm", source=sources, 
            LIBS=["cantera", 
                  "boost_filesystem", "boost_system"],
            LIBPATH=["/usr/local/lib"])
