env = Environment(CPPPATH=["/home/mbkumar/Research/Vlachos/cantera/include", 
                           "/home/mbkumar/Research/Vlachos/cantera/ext/eigen"],
                  CCFLAGS=["-std=c++0x", "-Wall", "-Wno-inline", "-fprofile-arcs", 
                           "-ftest-coverage", "-pthread"],
                  LINKFLAGS = ["-fprofile-arcs", "-ftest-coverage", "-pthread"])

sources = ["read_input.cpp", "util.cpp", "zerodReactor.cpp", "io.cpp"]

env.Program(target="hetero_ct", source=sources, 
            LIBS=["sundials_cvodes", "sundials_ida", "sundials_nvecserial", "cantera", "yaml-cpp"],
            #LIBS=[ "cantera"],
            LIBPATH=["/home/mbkumar/Research/Vlachos/cantera/build/lib", "/usr/lib64/"])
